apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: grpc
spec:
  tracing:
    samplerate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans
  features:
    - name: proxy.grpc
      enabled: true